[package]
name = "token_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.84.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.84.0", directory="noir-projects/aztec-nr/authwit"}
uint_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.84.0", directory="noir-projects/aztec-nr/uint-note" }
compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.84.0", directory="noir-projects/aztec-nr/compressed-string"}